POST http://localhost:3000/tournaments
Content-Type: application/json

{
    "name": "Test Tournament",
    "description": "This is a test tournament",
    "startTime": "2022-03-01 13:45:30",
    "endTime": "2022-03-01 13:59:30",
    "roundRobinDuration": 1,
    "playoffDuration": 1,
    "quarterFinalDuration": 1,
    "semiFinalDuration": 1,
    "finalDuration": 1
}

###
DELETE http://localhost:3000/tournaments/5